## region and cloud specific values
## fully isolated and only impact the cluster in the cloud provider region

controller:
  ingressClassResource:
    controllerValue: k8s.io/ingress-nginx
    default: true
    enabled: true
    name: nginx
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  minAvailable: "50%"
  service:
    ## https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  replicaCount: 2
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: "RuntimeDefault"
