apiVersion: v1
kind: Service
metadata:
  name: kubernetes-in-real-world-service
spec:
  selector:
    app: kubernetes-in-real-world-webapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
